# Generated by Django 3.1.5 on 2021-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikedClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipURL', models.CharField(max_length=250)),
                ('id_clip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=250)),
                ('id_streamer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('pictureURL', models.CharField(max_length=250)),
                ('id_twitch', models.CharField(max_length=30)),
                ('Follows', models.ManyToManyField(to='dtcapp.Streamer')),
                ('Likes', models.ManyToManyField(to='dtcapp.LikedClip')),
                ('Subscriptions', models.ManyToManyField(related_name='_user_Subscriptions_+', to='dtcapp.User')),
            ],
        ),
    ]
