# Generated by Django 3.1.5 on 2021-03-28 13:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('pictureURL', models.CharField(max_length=250)),
                ('id_twitch', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LikedClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipURL', models.CharField(max_length=250)),
                ('id_clip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=250)),
                ('id_streamer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtcapp.streamer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Follows',
            field=models.ManyToManyField(through='dtcapp.Following', to='dtcapp.Streamer'),
        ),
        migrations.AddField(
            model_name='user',
            name='Likes',
            field=models.ManyToManyField(to='dtcapp.LikedClip'),
        ),
        migrations.AddField(
            model_name='user',
            name='Subscriptions',
            field=models.ManyToManyField(related_name='_user_Subscriptions_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
